### ISSUE TITLE
Device ID for purple air sensor?

### ISSUE THREAD

**Issue by remotenw** [bpaauwe/udi-purpleair-poly#5]
any clue as to where to find the Device ID? the only id I can find associated with my purple air device is essentially a mac, and it is alphanumeric. the device is registered with purpleair & I believe is set to public as i can see it on the purple air map + wunderground.

thanks,

**Comment by bpaauwe** [comment]
It's in the link to share the station data on the map.

**Comment by remotenw** [comment]
excellent, works like a charm, thanks
